@startuml
actor User
participant "Cain's 3rd Left Toe (InputHandler)" as InputHandler #c912c9
participant "Cain's Left Foot (GameScreen)" as GameScreen #11f7f7
participant "Cain's Left Knee (PauseScreen)" as PauseScreen #11f7f7
participant Cain #00FF00
participant Abel #00FF00
participant Eve #yellow
participant Adam #red

activate GameScreen #11f7f7
Adam -> Cain: Switch screens (Start Game)
Cain -> GameScreen: SetScreen
loop "Game loop"
GameScreen -[#red]> GameScreen: startRender
GameScreen -[#red]> InputHandler: startHandle
InputHandler -[#blue]> GameScreen: endHandle
GameScreen -[#blue]> GameScreen: endRender
end loop
GameScreen -[#red]> InputHandler: startHandle
User -> InputHandler: "ESC"
InputHandler -[#blue]> GameScreen: Pause Game (endHandle)
GameScreen -> Cain: Pause Game
group Handle pause event
    Cain -[#red]> Adam: Pause Game (renderEvent)
    Adam -> Eve: Pause Server
    Eve -> Abel: Pause Server
    Abel ->]: Pause Server
    Adam -[#blue]> Cain: Switch screens
    Cain -> PauseScreen: SetScreen
    deactivate GameScreen
    activate PauseScreen #11f7f7
end
loop "Pause Loop"
    PauseScreen -[#red]> PauseScreen: startRender
    PauseScreen -[#red]> InputHandler: startHandle
    InputHandler -[#blue]> PauseScreen: endHandle
    PauseScreen -[#blue]> PauseScreen: endRender
end loop
deactivate PauseScreen
@enduml
