@startuml
actor User
participant GlobalInputListener as Listener #orange
participant MenuInputHandler #yellow
participant MenuScreen #11f7f7
participant Cain #00FF00
participant GameScreen #11f7f7
participant GameInputHandler #yellow
== Init ==
Cain -> Listener: Init listener
Cain -> MenuInputHandler: Init handler
Cain -> GameInputHandler: Init handler
== Main Menu ==
group Cain.setScreen(MENU)
    Cain -> MenuScreen: setScreen(MENU)
    activate MenuScreen #11f7f7
    Cain -> Listener: Listener.setHandler(MenuInputHandler)
    activate MenuInputHandler #yellow
end
loop "Menu loop"
    MenuScreen -[#red]> MenuInputHandler: startHandle
    User -> Listener: InputEvent
    Listener -> MenuInputHandler: HandleEvent
    MenuInputHandler -[#blue]> MenuScreen: endHandle
end loop
MenuScreen -[#red]> MenuInputHandler: startHandle
User -> Listener: Screen change event input
Listener -> MenuInputHandler: HandleEvent 
MenuInputHandler -[#blue]> MenuScreen: endHandle 
MenuScreen -> Cain: Change Screen
== Game Screen ==
group Cain.setScreen(GAME)
    deactivate MenuScreen
    Cain -> GameScreen: setScreen(GAME)
    activate GameScreen #11f7f7
    deactivate MenuInputHandler
    Cain -> Listener: Listener.setHandler(GameInputHandler)
    activate GameInputHandler #yellow
end
loop "Game loop"
    GameScreen -[#red]> GameInputHandler: startHandle
    User -> Listener: InputEvent
    Listener -> GameInputHandler: HandleEvent
    GameInputHandler -[#blue]> GameScreen: endHandle
end loop
@enduml


